-- SV_ESTADO_CALIDAD_AMBIENTAL definition

CREATE COLUMN TABLE "SV_ESTADO_CALIDAD_AMBIENTAL" ("ESTADO_CALIDAD_AMBIENTAL_CODE" NVARCHAR(20) NOT NULL ,
"NAME" NVARCHAR(100) NOT NULL ,
"DESCRIPTION" NVARCHAR(200),
CONSTRAINT "PK16" PRIMARY KEY ("ESTADO_CALIDAD_AMBIENTAL_CODE")) UNLOAD PRIORITY 5 AUTO MERGE;

-- SV_ESTADO_SOLICITUD_VISITA definition

CREATE COLUMN TABLE "SV_ESTADO_SOLICITUD_VISITA" ("ESTADO_SOLICITUD_VISITA_CODE" NVARCHAR(20) NOT NULL ,
"NAME" NVARCHAR(100) NOT NULL ,
"IS_ACTIVE" BOOLEAN DEFAULT FALSE NOT NULL ,
CONSTRAINT "PK39" PRIMARY KEY ("ESTADO_SOLICITUD_VISITA_CODE")) UNLOAD PRIORITY 5 AUTO MERGE;

-- SV_ESTADO_SSO definition

CREATE COLUMN TABLE "SV_ESTADO_SSO" ("ESTADO_SSO_CODE" NVARCHAR(20) NOT NULL ,
"NAME" NVARCHAR(100) NOT NULL ,
"DESCRIPTION" NVARCHAR(200),
CONSTRAINT "PK16_1" PRIMARY KEY ("ESTADO_SSO_CODE")) UNLOAD PRIORITY 5 AUTO MERGE;

-- SV_PARAMETRO definition

CREATE COLUMN TABLE "SV_PARAMETRO" ("PARAMETRO_CODE" NVARCHAR(50) NOT NULL ,
"DESCRIPTION" NVARCHAR(100),
"NAME" NVARCHAR(100) NOT NULL ,
"VALOR" NVARCHAR(250) NOT NULL ,
CONSTRAINT "PK13" PRIMARY KEY ("PARAMETRO_CODE")) UNLOAD PRIORITY 5 AUTO MERGE;

-- SV_ROL definition

CREATE COLUMN TABLE "SV_ROL" ("ROL_CODE" NVARCHAR(50) NOT NULL ,
"ROL_NAME" NVARCHAR(100) NOT NULL ,
"ROL_DESCRIPTION" NVARCHAR(200),
CONSTRAINT "PK8" PRIMARY KEY ("ROL_CODE")) UNLOAD PRIORITY 5 AUTO MERGE;

-- SV_SEDE definition

CREATE COLUMN TABLE "SV_SEDE" ("SEDE_ID" NVARCHAR(36) NOT NULL ,
"NAME" NVARCHAR(100) NOT NULL ,
"AMBITO" NVARCHAR(20) NOT NULL ,
CONSTRAINT "PK6" PRIMARY KEY ("SEDE_ID")) UNLOAD PRIORITY 5 AUTO MERGE;

-- SV_TIPO_ACTIVIDAD_ALTO_RIESGO definition

CREATE COLUMN TABLE "SV_TIPO_ACTIVIDAD_ALTO_RIESGO" ("TIPO_ACTIVIDAD_ALTO_RIESGO_CODE" NVARCHAR(50) NOT NULL ,
"DESCRIPTION" NVARCHAR(100) NOT NULL ,
"IS_ACTIVE" BOOLEAN DEFAULT FALSE NOT NULL ,
CONSTRAINT "PK14" PRIMARY KEY ("TIPO_ACTIVIDAD_ALTO_RIESGO_CODE")) UNLOAD PRIORITY 5 AUTO MERGE;

-- SV_TIPO_DOCUMENTO_IDENTIDAD definition

CREATE COLUMN TABLE "SV_TIPO_DOCUMENTO_IDENTIDAD" ("TIPO_DOCUMENTO_IDENTIDAD_CODE" NVARCHAR(50) NOT NULL ,
"NAME" NVARCHAR(100),
"IS_ACTIVE" BOOLEAN DEFAULT FALSE NOT NULL ,
"EXPRESION_REGULAR" NVARCHAR(100),
CONSTRAINT "PK18" PRIMARY KEY ("TIPO_DOCUMENTO_IDENTIDAD_CODE")) UNLOAD PRIORITY 5 AUTO MERGE;

-- SV_TIPO_DOCUMENTO_PLANILLA definition

CREATE COLUMN TABLE "SV_TIPO_DOCUMENTO_PLANILLA" ("TIPO_DOCUMENTO_PLANILLA_CODE" NVARCHAR(20) NOT NULL ,
"DESCRIPTION" NVARCHAR(200),
"AMBITO" NVARCHAR(50),
"INFLUENCIA" NVARCHAR(50),
"DEPENDENCIA" NVARCHAR(200),
"CAMPO_PLANTILLA_LF" NVARCHAR(200),
"OBLIGATORIO" BOOLEAN DEFAULT FALSE NOT NULL ,
"VENCIMIENTO" BOOLEAN DEFAULT FALSE NOT NULL ,
CONSTRAINT "PK21" PRIMARY KEY ("TIPO_DOCUMENTO_PLANILLA_CODE")) UNLOAD PRIORITY 5 AUTO MERGE;

-- SV_USUARIO definition

CREATE COLUMN TABLE "SV_USUARIO" ("USUARIO_ID" NVARCHAR(36) NOT NULL ,
"NOMBRE" NVARCHAR(100),
"APELLIDOS" NVARCHAR(200),
"EMAIL" NVARCHAR(100),
"IDENTIFICADOR_EXTERNO" NVARCHAR(50),
CONSTRAINT "PK7" PRIMARY KEY ("USUARIO_ID")) UNLOAD PRIORITY 5 AUTO MERGE;


------ TIENEN LLAVES FORÁNEAS ------

-- SV_AREA definition

CREATE COLUMN TABLE "SV_AREA" ("AREA_ID" NVARCHAR(36) NOT NULL ,
"NAME" NVARCHAR(100) NOT NULL ,
"AMBITO" NVARCHAR(100),
"OPERATIVA" NVARCHAR(100),
"SEDE_ID" NVARCHAR(36) NOT NULL ,
CONSTRAINT "PK28" PRIMARY KEY ("AREA_ID")) UNLOAD PRIORITY 5 AUTO MERGE ;

ALTER TABLE "SV_AREA" ADD CONSTRAINT "REFSEDE31" FOREIGN KEY ("SEDE_ID") REFERENCES "SV_SEDE" ("SEDE_ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;


-- SV_ADJUNTO definition

CREATE COLUMN TABLE "SV_ADJUNTO" ("ADJUNTO_ID" NVARCHAR(36) NOT NULL ,
"NOMBRE_ARCHIVO" NVARCHAR(200) NOT NULL ,
"ID_REPOSITORIO" NVARCHAR(50),
"CLASIFICATION" NVARCHAR(50) NOT NULL ,
"FECHA_DOCUMENTO" DATE,
"FECHA_VENCIMIENTO" DATE,
"RUTA_RELATIVA" NVARCHAR(200),
"SSO_COMENTARIO_REVISION" NVARCHAR(200),
"CA_COMENTARIO_REVISION" NVARCHAR(200),
"MOTIVO" NVARCHAR(200),
"PROVEEDOR_ID" NVARCHAR(36),
"TRABAJADOR_ID" NVARCHAR(36),
"TIPO_DOCUMENTO_PLANILLA_CODE" NVARCHAR(20),
"SOLICITUD_VISITA_ID" NVARCHAR(36),
"TIPO_ACTIVIDAD_ALTO_RIESGO_CODE" NVARCHAR(50),
CONSTRAINT "PK19" PRIMARY KEY ("ADJUNTO_ID")) UNLOAD PRIORITY 5 AUTO MERGE ;

ALTER TABLE "SV_ADJUNTO" ADD CONSTRAINT "REFPROVEEDOR22" FOREIGN KEY ("PROVEEDOR_ID") REFERENCES "SV_PROVEEDOR" ("PROVEEDOR_ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "SV_ADJUNTO" ADD CONSTRAINT "REFTRABAJADOR23" FOREIGN KEY ("TRABAJADOR_ID") REFERENCES "SV_TRABAJADOR" ("TRABAJADOR_ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "SV_ADJUNTO" ADD CONSTRAINT "REFTIPO_DOCUMENTO_PLANILLA24" FOREIGN KEY ("TIPO_DOCUMENTO_PLANILLA_CODE") REFERENCES "SV_TIPO_DOCUMENTO_PLANILLA" ("TIPO_DOCUMENTO_PLANILLA_CODE") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "SV_ADJUNTO" ADD CONSTRAINT "REFSOLICITUD_VISISTA43" FOREIGN KEY ("SOLICITUD_VISITA_ID") REFERENCES "SV_SOLICITUD_VISISTA" ("SOLICITUD_VISITA_ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "SV_ADJUNTO" ADD CONSTRAINT "REFTIPO_ACTIVIDAD_ALTO_RIESGO50" FOREIGN KEY ("TIPO_ACTIVIDAD_ALTO_RIESGO_CODE") REFERENCES "SV_TIPO_ACTIVIDAD_ALTO_RIESGO" ("TIPO_ACTIVIDAD_ALTO_RIESGO_CODE") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

-- SV_PERSONA_RESTRINGIDA definition

CREATE COLUMN TABLE "SV_PERSONA_RESTRINGIDA" ("PERSONA_RESTRINGIDA_ID" NVARCHAR(36) NOT NULL ,
"TIPO_DOCUMENTO_IDENTIDAD_CODE" NVARCHAR(50) NOT NULL ,
"NUMERO_DOCUMENTO" NVARCHAR(50) NOT NULL ,
"LICENCIA_CONDUCIR" NVARCHAR(50),
"NOMBRE_COMPLETO" NVARCHAR(200),
"USUARIO_REPORTA" NVARCHAR(200),
"RESTRINGIDO_EL" LONGDATE,
"RESTRINGIDO_HASTA" LONGDATE,
"OBSERVACIONES" NVARCHAR(250),
"SEDE_ORIGINADORA_ID" NVARCHAR(36),
CONSTRAINT "PK12" PRIMARY KEY ("PERSONA_RESTRINGIDA_ID")) UNLOAD PRIORITY 5 AUTO MERGE ;

ALTER TABLE "SV_PERSONA_RESTRINGIDA" ADD CONSTRAINT "REFTIPO_DOCUMENTO_IDENTIDAD26" FOREIGN KEY ("TIPO_DOCUMENTO_IDENTIDAD_CODE") REFERENCES "SV_TIPO_DOCUMENTO_IDENTIDAD" ("TIPO_DOCUMENTO_IDENTIDAD_CODE") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "SV_PERSONA_RESTRINGIDA" ADD CONSTRAINT "REFSEDE28" FOREIGN KEY ("SEDE_ORIGINADORA_ID") REFERENCES "SV_SEDE" ("SEDE_ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

-- SV_PERSONAL definition

CREATE COLUMN TABLE "SV_PERSONAL" ("PERSONAL_ID" NVARCHAR(36) NOT NULL ,
"USUARIO" NVARCHAR(100) NOT NULL ,
"NOMBRE_USUARIO" NVARCHAR(200),
"CODIGO" NVARCHAR(100),
"DESCRIPCION" NVARCHAR(200),
"AMBITO" NVARCHAR(100),
"INFLUENCIA" NVARCHAR(100),
"DEPENDENCIA" NVARCHAR(100),
"CAMPO_PLANTILLA_LF" NVARCHAR(100),
"OBLIGATORIO" NVARCHAR(2),
"VENCIMIENTO" NVARCHAR(10),
"NUMERO_CASO" NVARCHAR(20),
"MENSAJE" NVARCHAR(200),
"TIPO_DOCUMENTO_IDENTIDAD_CODE" NVARCHAR(50),
CONSTRAINT "PK29" PRIMARY KEY ("PERSONAL_ID")) UNLOAD PRIORITY 5 AUTO MERGE ;

ALTER TABLE "SV_PERSONAL" ADD CONSTRAINT "SV_PERSONAL_SV_TIPO_DOCUMENTO_IDENTIDAD_FK" FOREIGN KEY ("TIPO_DOCUMENTO_IDENTIDAD_CODE") REFERENCES "SV_TIPO_DOCUMENTO_IDENTIDAD" ("TIPO_DOCUMENTO_IDENTIDAD_CODE") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

-- SV_PERSONAL_SEDE definition

CREATE COLUMN TABLE "SV_PERSONAL_SEDE" ("PERSONAL_SEDE_ID" NVARCHAR(36) NOT NULL ,
"PERSONAL_ID" NVARCHAR(36) NOT NULL ,
"SEDE_ID" NVARCHAR(36) NOT NULL ,
"IS_ACTIVE" BOOLEAN DEFAULT FALSE NOT NULL ,
CONSTRAINT "PK41" PRIMARY KEY ("PERSONAL_SEDE_ID")) UNLOAD PRIORITY 5 AUTO MERGE ;

ALTER TABLE "SV_PERSONAL_SEDE" ADD CONSTRAINT "REFPERSONAL1" FOREIGN KEY ("PERSONAL_ID") REFERENCES "SV_PERSONAL" ("PERSONAL_ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "SV_PERSONAL_SEDE" ADD CONSTRAINT "REFSEDE4" FOREIGN KEY ("SEDE_ID") REFERENCES "SV_SEDE" ("SEDE_ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

-- SV_PROVEEDOR definition

CREATE COLUMN TABLE "SV_PROVEEDOR" ("PROVEEDOR_ID" NVARCHAR(36) NOT NULL ,
"ESTADO_CALIDAD_AMBIENTAL_CODE" NVARCHAR(20) NOT NULL ,
"NRO_DOCUMENTO_IDENTIDAD" NVARCHAR(20),
"NOMBRE_FISCAL" NVARCHAR(200),
"EMAIL" NVARCHAR(100),
"DIRECCION" NVARCHAR(200),
"CONTACTO_PRINCIPAL" NVARCHAR(200),
"CONTACTO_PRINCIPAL_TELEFONO" NVARCHAR(20),
"SSO_TIENE_VIGENCIA" BOOLEAN DEFAULT FALSE NOT NULL ,
"SSO_FECHA_INICIO_VIGENCIA" DATE,
"SSO_FECHA_FIN_VIGENCIA" NVARCHAR(10),
"SSO_MOTIVO" NVARCHAR(200),
"SSO_USUARIO_EVALUADOR" NVARCHAR(50),
"SSO_FECHA_EVALUACION" LONGDATE,
"IND_REALIZA_ACTIVIDAD_ALTO_RIESGO" BOOLEAN DEFAULT FALSE NOT NULL ,
"IND_REALIZA_ACTIVIDAD_A_BORDO" BOOLEAN DEFAULT FALSE NOT NULL ,
"CA_TIENE_VIGENCIA" BOOLEAN DEFAULT FALSE NOT NULL ,
"CA_FECHA_INICIO_VIGENCIA" DATE,
"CA_FECHA_FIN_VIGENCIA" DATE,
"CA_MOTIVO" NVARCHAR(200),
"CA_USUARIO_EVALUADOR" NVARCHAR(50),
"CA_FECHA_EVALUACION" LONGDATE,
"ORIGEN_REGISTRO" NVARCHAR(50),
"ESTADO_SSO_CODE" NVARCHAR(20) NOT NULL ,
"IND_PROVEEDOR_NOTIFICADO_CREACION" BOOLEAN,
"TELEFONO" NVARCHAR(20),
"NACIONAL" BOOLEAN,
CONSTRAINT "PK4" PRIMARY KEY ("PROVEEDOR_ID")) UNLOAD PRIORITY 5 AUTO MERGE ;

ALTER TABLE "SV_PROVEEDOR" ADD CONSTRAINT "REFESTADO_CALIDAD_AMBIENTAL7" FOREIGN KEY ("ESTADO_CALIDAD_AMBIENTAL_CODE") REFERENCES "SV_ESTADO_CALIDAD_AMBIENTAL" ("ESTADO_CALIDAD_AMBIENTAL_CODE") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "SV_PROVEEDOR" ADD CONSTRAINT "REFESTADO_SSO38" FOREIGN KEY ("ESTADO_SSO_CODE") REFERENCES "SV_ESTADO_SSO" ("ESTADO_SSO_CODE") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

-- SV_PROVEEDOR_SEDE definition

CREATE COLUMN TABLE "SV_PROVEEDOR_SEDE" ("PROVEEDOR_SEDE_ID" NVARCHAR(36) NOT NULL ,
"PROVEEDOR_ID" NVARCHAR(36) NOT NULL ,
"SEDE_ID" NVARCHAR(36) NOT NULL ,
"IS_ACTIVE" BOOLEAN DEFAULT FALSE NOT NULL ,
CONSTRAINT "PK10" PRIMARY KEY ("PROVEEDOR_SEDE_ID")) UNLOAD PRIORITY 5 AUTO MERGE ;

ALTER TABLE "SV_PROVEEDOR_SEDE" ADD CONSTRAINT "REFPROVEEDOR2" FOREIGN KEY ("PROVEEDOR_ID") REFERENCES "SV_PROVEEDOR" ("PROVEEDOR_ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "SV_PROVEEDOR_SEDE" ADD CONSTRAINT "REFSEDE3" FOREIGN KEY ("SEDE_ID") REFERENCES "SV_SEDE" ("SEDE_ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

-- SV_PROVEEDOR_TIPO_ACTIVIDAD_ALTO_RIESGO definition

CREATE COLUMN TABLE "SV_PROVEEDOR_TIPO_ACTIVIDAD_ALTO_RIESGO" ("PROVEEDOR_TIPO_ACTIVIDAD_ALTO_RIESGO_ID" NVARCHAR(36) NOT NULL ,
"TIPO_ACTIVIDAD_ALTO_RIESGO_CODE" NVARCHAR(50) NOT NULL ,
"PROVEEDOR_ID" NVARCHAR(36) NOT NULL ,
"IS_ACTIVE" BOOLEAN,
CONSTRAINT "PK24" PRIMARY KEY ("PROVEEDOR_TIPO_ACTIVIDAD_ALTO_RIESGO_ID")) UNLOAD PRIORITY 5 AUTO MERGE ;

ALTER TABLE "SV_PROVEEDOR_TIPO_ACTIVIDAD_ALTO_RIESGO" ADD CONSTRAINT "REFTIPO_ACTIVIDAD_ALTO_RIESGO18" FOREIGN KEY ("TIPO_ACTIVIDAD_ALTO_RIESGO_CODE") REFERENCES "SV_TIPO_ACTIVIDAD_ALTO_RIESGO" ("TIPO_ACTIVIDAD_ALTO_RIESGO_CODE") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "SV_PROVEEDOR_TIPO_ACTIVIDAD_ALTO_RIESGO" ADD CONSTRAINT "REFPROVEEDOR19" FOREIGN KEY ("PROVEEDOR_ID") REFERENCES "SV_PROVEEDOR" ("PROVEEDOR_ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

-- SV_TRABAJADOR definition

CREATE COLUMN TABLE "SV_TRABAJADOR" ("TRABAJADOR_ID" NVARCHAR(36) NOT NULL ,
"PROVEEDOR_ID" NVARCHAR(36) NOT NULL ,
"TIPO_DOCUMENTO_IDENTIDAD_CODE" NVARCHAR(50) NOT NULL ,
"NRO_DOCUMENTO_IDENTIDAD" NVARCHAR(50),
"NOMBRE" NVARCHAR(100) NOT NULL ,
"TELEFONO" NVARCHAR(20),
"EMAIL" NVARCHAR(100),
"SSO_MOTIVO" NVARCHAR(200),
"SO_TIENE_VIGENCIA" BOOLEAN DEFAULT FALSE NOT NULL ,
"SSO_FECHA_INICIO_VIGENCIA" DATE,
"SSO_FECHA_FIN_VIGENCIA" DATE,
"IND_TRABAJO_ALTO_RIESGO" BOOLEAN DEFAULT FALSE NOT NULL ,
"IND_PREVENCIONISTA" BOOLEAN DEFAULT FALSE NOT NULL ,
"ESTADO_SSO_CODE" NVARCHAR(20) NOT NULL ,
"IS_ACTIVE" BOOLEAN DEFAULT FALSE NOT NULL ,
CONSTRAINT "PK5" PRIMARY KEY ("TRABAJADOR_ID")) UNLOAD PRIORITY 5 AUTO MERGE ;

ALTER TABLE "SV_TRABAJADOR" ADD CONSTRAINT "REFPROVEEDOR1" FOREIGN KEY ("PROVEEDOR_ID") REFERENCES "SV_PROVEEDOR" ("PROVEEDOR_ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "SV_TRABAJADOR" ADD CONSTRAINT "REFTIPO_DOCUMENTO_IDENTIDAD10" FOREIGN KEY ("TIPO_DOCUMENTO_IDENTIDAD_CODE") REFERENCES "SV_TIPO_DOCUMENTO_IDENTIDAD" ("TIPO_DOCUMENTO_IDENTIDAD_CODE") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "SV_TRABAJADOR" ADD CONSTRAINT "REFESTADO_SSO39" FOREIGN KEY ("ESTADO_SSO_CODE") REFERENCES "SV_ESTADO_SSO" ("ESTADO_SSO_CODE") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

-- SV_ZONA definition

CREATE COLUMN TABLE "SV_ZONA" ("ZONA_ID" NVARCHAR(36) NOT NULL ,
"NAME" NVARCHAR(100) NOT NULL ,
"OPERATIVA" NVARCHAR(50),
"SEDE_ID" NVARCHAR(36) NOT NULL ,
CONSTRAINT "PK32" PRIMARY KEY ("ZONA_ID")) UNLOAD PRIORITY 5 AUTO MERGE ;

ALTER TABLE "SV_ZONA" ADD CONSTRAINT "REFSEDE34" FOREIGN KEY ("SEDE_ID") REFERENCES "SV_SEDE" ("SEDE_ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

-- SV_SOLICITUD_VISISTA definition

CREATE COLUMN TABLE "SV_SOLICITUD_VISISTA" ("SOLICITUD_VISITA_ID" NVARCHAR(36) NOT NULL ,
"CODIGO_VISITA" NVARCHAR(20) NOT NULL ,
"CODIGO_SISTEMA_EXTERNO" NVARCHAR(50),
"FECHA_INICIO" LONGDATE,
"FECHA_FIN" LONGDATE,
"MOTIVO_VISITA" NVARCHAR(200),
"FECHA_APROBACION_PERSONA_VISITADA" LONGDATE,
"FECHA_OBSERVACION_ADMINISTRADOR" LONGDATE,
"OBSERVACIONES" NVARCHAR(250),
"NRO_ORDEN_SERVICIO" NVARCHAR(50) NOT NULL ,
"IND_ACTIVIDAD_ALTO_RIESGO" BOOLEAN DEFAULT FALSE NOT NULL ,
"IND_ACTIVIDAD_A_BORDO" BOOLEAN DEFAULT FALSE NOT NULL ,
"IND_REQUIERE_ANDAMIOS" BOOLEAN DEFAULT FALSE NOT NULL ,
"IND_REQUIERE_GRUA" BOOLEAN DEFAULT FALSE NOT NULL ,
"IND_REQUIERE_EQUIPOS_MOVILES" BOOLEAN DEFAULT FALSE NOT NULL ,
"IND_TRABAJO_BUCEO" BOOLEAN DEFAULT FALSE NOT NULL ,
"SSO_MOTIVO" NVARCHAR(200),
"SSO_DESCARGO" NVARCHAR(200),
"CA_MOTIVO" NVARCHAR(200),
"CA_DESCARGO" NVARCHAR(200),
"ESTADO_SSO_CODE" NVARCHAR(20) NOT NULL ,
"ESTADO_CALIDAD_AMBIENTAL_CODE" NVARCHAR(20) NOT NULL ,
"ESTADO_SOLICITUD_VISITA_CODE" NVARCHAR(20) NOT NULL ,
"SEDE_ID" NVARCHAR(36) NOT NULL ,
"PROVEEDOR_ID" NVARCHAR(36) NOT NULL ,
"PERSONAL_ID" NVARCHAR(36),
CONSTRAINT "PK26" PRIMARY KEY ("SOLICITUD_VISITA_ID")) UNLOAD PRIORITY 5 AUTO MERGE ;

ALTER TABLE "SV_SOLICITUD_VISISTA" ADD CONSTRAINT "REFESTADO_SSO41" FOREIGN KEY ("ESTADO_SSO_CODE") REFERENCES "SV_ESTADO_SSO" ("ESTADO_SSO_CODE") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "SV_SOLICITUD_VISISTA" ADD CONSTRAINT "REFESTADO_CALIDAD_AMBIENTAL42" FOREIGN KEY ("ESTADO_CALIDAD_AMBIENTAL_CODE") REFERENCES "SV_ESTADO_CALIDAD_AMBIENTAL" ("ESTADO_CALIDAD_AMBIENTAL_CODE") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "SV_SOLICITUD_VISISTA" ADD CONSTRAINT "REFESTADO_SOLICITUD_VISITA53" FOREIGN KEY ("ESTADO_SOLICITUD_VISITA_CODE") REFERENCES "SV_ESTADO_SOLICITUD_VISITA" ("ESTADO_SOLICITUD_VISITA_CODE") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "SV_SOLICITUD_VISISTA" ADD CONSTRAINT "REFSEDE54" FOREIGN KEY ("SEDE_ID") REFERENCES "SV_SEDE" ("SEDE_ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "SV_SOLICITUD_VISISTA" ADD CONSTRAINT "REFPROVEEDOR55" FOREIGN KEY ("PROVEEDOR_ID") REFERENCES "SV_PROVEEDOR" ("PROVEEDOR_ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "SV_SOLICITUD_VISISTA" ADD CONSTRAINT "SV_SOLICITUD_VISISTA_SV_PERSONAL_FK" FOREIGN KEY ("PERSONAL_ID") REFERENCES "SV_PERSONAL" ("PERSONAL_ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

-- SV_SOLICITUD_VISITA_AREA_AUTORIZADORA definition

CREATE COLUMN TABLE "SV_SOLICITUD_VISITA_AREA_AUTORIZADORA" ("SOLICITUD_VISITA_AREA_AUTORIZADORA_ID" NVARCHAR(36) NOT NULL ,
"IS_ACTIVE" BOOLEAN DEFAULT FALSE NOT NULL ,
"SOLICITUD_VISITA_ID" NVARCHAR(36) NOT NULL ,
"AREA_AUTORIZADORA_ID" NVARCHAR(36) NOT NULL ,
CONSTRAINT "PK30" PRIMARY KEY ("SOLICITUD_VISITA_AREA_AUTORIZADORA_ID")) UNLOAD PRIORITY 5 AUTO MERGE ;

ALTER TABLE "SV_SOLICITUD_VISITA_AREA_AUTORIZADORA" ADD CONSTRAINT "REFSOLICITUD_VISISTA32" FOREIGN KEY ("SOLICITUD_VISITA_ID") REFERENCES "SV_SOLICITUD_VISISTA" ("SOLICITUD_VISITA_ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "SV_SOLICITUD_VISITA_AREA_AUTORIZADORA" ADD CONSTRAINT "REFAREA33" FOREIGN KEY ("AREA_AUTORIZADORA_ID") REFERENCES "SV_AREA" ("AREA_ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

-- SV_SOLICITUD_VISITA_DETALLE definition

CREATE COLUMN TABLE "SV_SOLICITUD_VISITA_DETALLE" ("SOLICITUD_VISITA_DETALLE_ID" NVARCHAR(36) NOT NULL ,
"PROVEEDOR_COMENTARIO" NVARCHAR(200),
"SOLICITUD_VISITA_ID" NVARCHAR(36) NOT NULL ,
"TRABAJADOR_ID" NVARCHAR(36) NOT NULL ,
CONSTRAINT "PK38" PRIMARY KEY ("SOLICITUD_VISITA_DETALLE_ID")) UNLOAD PRIORITY 5 AUTO MERGE ;

ALTER TABLE "SV_SOLICITUD_VISITA_DETALLE" ADD CONSTRAINT "REFSOLICITUD_VISISTA51" FOREIGN KEY ("SOLICITUD_VISITA_ID") REFERENCES "SV_SOLICITUD_VISISTA" ("SOLICITUD_VISITA_ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "SV_SOLICITUD_VISITA_DETALLE" ADD CONSTRAINT "REFTRABAJADOR52" FOREIGN KEY ("TRABAJADOR_ID") REFERENCES "SV_TRABAJADOR" ("TRABAJADOR_ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

-- SV_SOLICITUD_VISITA_EQUIPO definition

CREATE COLUMN TABLE "SV_SOLICITUD_VISITA_EQUIPO" ("SOLICITUD_VISITA_EQUIPO_ID" NVARCHAR(36) NOT NULL ,
"DESCRIPCION" NVARCHAR(100) NOT NULL ,
"MARCA" NVARCHAR(50),
"MODELO" NVARCHAR(50),
"NUMERO_SERIE" NVARCHAR(30),
"TIPO_EQUIPO" NVARCHAR(50),
"CODIGO_EQUIPO" NVARCHAR(50),
"CANTIDAD" DECIMAL(10, 3),
"SOLICITUD_VISITA_ID" NVARCHAR(36) NOT NULL ,
CONSTRAINT "PK36" PRIMARY KEY ("SOLICITUD_VISITA_EQUIPO_ID")) UNLOAD PRIORITY 5 AUTO MERGE ;

ALTER TABLE "SV_SOLICITUD_VISITA_EQUIPO" ADD CONSTRAINT "REFSOLICITUD_VISISTA45" FOREIGN KEY ("SOLICITUD_VISITA_ID") REFERENCES "SV_SOLICITUD_VISISTA" ("SOLICITUD_VISITA_ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

-- SV_SOLICITUD_VISITA_EVENTO definition

CREATE COLUMN TABLE "SV_SOLICITUD_VISITA_EVENTO" ("SOLICITUD_VISITA_EVENTO_ID" NVARCHAR(36) NOT NULL ,
"FECHA_EVENTO" LONGDATE NOT NULL ,
"USUARIO" NVARCHAR(50),
"EVENTO" NVARCHAR(100) NOT NULL ,
"AMBITO" NVARCHAR(100),
"REVISION" NVARCHAR(100),
"RESPUESTA_USUARIO" NVARCHAR(200),
"SOLICITUD_VISITA_ID" NVARCHAR(36) NOT NULL ,
CONSTRAINT "PK40" PRIMARY KEY ("SOLICITUD_VISITA_EVENTO_ID")) UNLOAD PRIORITY 5 AUTO MERGE ;

ALTER TABLE "SV_SOLICITUD_VISITA_EVENTO" ADD CONSTRAINT "REFSOLICITUD_VISISTA55" FOREIGN KEY ("SOLICITUD_VISITA_ID") REFERENCES "SV_SOLICITUD_VISISTA" ("SOLICITUD_VISITA_ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

-- SV_SOLICITUD_VISITA_MATERIAL definition

CREATE COLUMN TABLE "SV_SOLICITUD_VISITA_MATERIAL" ("SOLICITUD_VISITA_MATERIAL_ID" NVARCHAR(36) NOT NULL ,
"DESCRIPCION" NVARCHAR(100) NOT NULL ,
"CANTIDAD" DECIMAL(10, 3),
"UNIDAD_MEDIDA" NVARCHAR(10),
"SOLICITUD_VISITA_ID" NVARCHAR(36) NOT NULL ,
CONSTRAINT "PK35" PRIMARY KEY ("SOLICITUD_VISITA_MATERIAL_ID")) UNLOAD PRIORITY 5 AUTO MERGE ;

ALTER TABLE "SV_SOLICITUD_VISITA_MATERIAL" ADD CONSTRAINT "REFSOLICITUD_VISISTA44" FOREIGN KEY ("SOLICITUD_VISITA_ID") REFERENCES "SV_SOLICITUD_VISISTA" ("SOLICITUD_VISITA_ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

-- SV_SOLICITUD_VISITA_TIPO_ACTIVIDAD_ALTO_RIESGO definition

CREATE COLUMN TABLE "SV_SOLICITUD_VISITA_TIPO_ACTIVIDAD_ALTO_RIESGO" ("SOLICITUD_VISITA_TIPO_ACTIVIDAD_ALTO_RIESGO_ID" NVARCHAR(36) NOT NULL ,
"IS_ACTIVE" BOOLEAN DEFAULT FALSE NOT NULL ,
"TIPO_ACTIVIDAD_ALTO_RIESGO_CODE" NVARCHAR(50) NOT NULL ,
"SOLICITUD_VISITA_ID" NVARCHAR(36) NOT NULL ,
CONSTRAINT "PK37" PRIMARY KEY ("SOLICITUD_VISITA_TIPO_ACTIVIDAD_ALTO_RIESGO_ID")) UNLOAD PRIORITY 5 AUTO MERGE ;

ALTER TABLE "SV_SOLICITUD_VISITA_TIPO_ACTIVIDAD_ALTO_RIESGO" ADD CONSTRAINT "REFTIPO_ACTIVIDAD_ALTO_RIESGO47" FOREIGN KEY ("TIPO_ACTIVIDAD_ALTO_RIESGO_CODE") REFERENCES "SV_TIPO_ACTIVIDAD_ALTO_RIESGO" ("TIPO_ACTIVIDAD_ALTO_RIESGO_CODE") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "SV_SOLICITUD_VISITA_TIPO_ACTIVIDAD_ALTO_RIESGO" ADD CONSTRAINT "REFSOLICITUD_VISISTA48" FOREIGN KEY ("SOLICITUD_VISITA_ID") REFERENCES "SV_SOLICITUD_VISISTA" ("SOLICITUD_VISITA_ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

-- SV_SOLICITUD_VISITA_ZONA definition

CREATE COLUMN TABLE "SV_SOLICITUD_VISITA_ZONA" ("SOLICITUD_VISITA_ZONA_ID" NVARCHAR(36) NOT NULL ,
"IS_ACTIVE" BOOLEAN DEFAULT FALSE NOT NULL ,
"ZONA_ID" NVARCHAR(36) NOT NULL ,
"SOLICITUD_VISITA_ID" NVARCHAR(36) NOT NULL ,
CONSTRAINT "PK33" PRIMARY KEY ("SOLICITUD_VISITA_ZONA_ID")) UNLOAD PRIORITY 5 AUTO MERGE ;

ALTER TABLE "SV_SOLICITUD_VISITA_ZONA" ADD CONSTRAINT "REFZONA35" FOREIGN KEY ("ZONA_ID") REFERENCES "SV_ZONA" ("ZONA_ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "SV_SOLICITUD_VISITA_ZONA" ADD CONSTRAINT "REFSOLICITUD_VISISTA36" FOREIGN KEY ("SOLICITUD_VISITA_ID") REFERENCES "SV_SOLICITUD_VISISTA" ("SOLICITUD_VISITA_ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

-- SV_SOLICITUD_VISITA_HISTORIAL definition

CREATE COLUMN TABLE "SV_SOLICITUD_VISITA_HISTORIAL" ("SOLICITUD_VISITA_HISTORIAL_ID" NVARCHAR(36) NOT NULL ,
"SOLICITUD_VISITA_ID" NVARCHAR(36),
"ESTADO_SOLICITUD_VISITA_CODE" NVARCHAR(20),
"FECHA_HORA" LONGDATE,
CONSTRAINT "SV_SOLICITUD_VISITA_HISTORIAL_PK" PRIMARY KEY ("SOLICITUD_VISITA_HISTORIAL_ID")) UNLOAD PRIORITY 5 AUTO MERGE ;

ALTER TABLE "SV_SOLICITUD_VISITA_HISTORIAL" ADD CONSTRAINT "SV_SOLICITUD_VISITA_HISTORIAL_SV_SOLICITUD_VISISTA_FK" FOREIGN KEY ("SOLICITUD_VISITA_ID") REFERENCES "SV_SOLICITUD_VISISTA" ("SOLICITUD_VISITA_ID") ON
    UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "SV_SOLICITUD_VISITA_HISTORIAL" ADD CONSTRAINT "SV_SOLICITUD_VISITA_HISTORIAL_SV_ESTADO_SOLICITUD_VISITA_FK" FOREIGN KEY ("ESTADO_SOLICITUD_VISITA_CODE") REFERENCES "SV_ESTADO_SOLICITUD_VISITA" ("ESTADO_SOLICITUD_VISITA_CODE") ON
    UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

-- SV_TRABAJADOR_TIPO_ACTIVIDAD_ALTO_RIESGO definition

CREATE COLUMN TABLE "SV_TRABAJADOR_TIPO_ACTIVIDAD_ALTO_RIESGO" ("TRABAJADOR_TIPO_ACTIVIDAD_ALTO_RIESGO_ID" NVARCHAR(36) NOT NULL ,
"TRABAJADOR_ID" NVARCHAR(36) NOT NULL ,
"TIPO_ACTIVIDAD_ALTO_RIESGO_CODE" NVARCHAR(50) NOT NULL ,
"IS_ACTIVE" BOOLEAN DEFAULT FALSE NOT NULL ,
CONSTRAINT "PK25" PRIMARY KEY ("TRABAJADOR_TIPO_ACTIVIDAD_ALTO_RIESGO_ID")) UNLOAD PRIORITY 5 AUTO MERGE ;

ALTER TABLE "SV_TRABAJADOR_TIPO_ACTIVIDAD_ALTO_RIESGO" ADD CONSTRAINT "REFTRABAJADOR20" FOREIGN KEY ("TRABAJADOR_ID") REFERENCES "SV_TRABAJADOR" ("TRABAJADOR_ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "SV_TRABAJADOR_TIPO_ACTIVIDAD_ALTO_RIESGO" ADD CONSTRAINT "REFTIPO_ACTIVIDAD_ALTO_RIESGO21" FOREIGN KEY ("TIPO_ACTIVIDAD_ALTO_RIESGO_CODE") REFERENCES "SV_TIPO_ACTIVIDAD_ALTO_RIESGO" ("TIPO_ACTIVIDAD_ALTO_RIESGO_CODE") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

-- SV_USUARIO_ROL_SEDE definition

CREATE COLUMN TABLE "SV_USUARIO_ROL_SEDE" ("USUARIO_ROL_SEDE_ID" NVARCHAR(36) NOT NULL ,
"USUARIO_ID" NVARCHAR(36) NOT NULL ,
"ROL_CODE" NVARCHAR(50) NOT NULL ,
"SEDE_ID" NVARCHAR(36) NOT NULL ,
"IS_ACTIVE" BOOLEAN DEFAULT FALSE NOT NULL ,
CONSTRAINT "PK9" PRIMARY KEY ("USUARIO_ROL_SEDE_ID")) UNLOAD PRIORITY 5 AUTO MERGE ;

ALTER TABLE "SV_USUARIO_ROL_SEDE" ADD CONSTRAINT "REFUSUARIO4" FOREIGN KEY ("USUARIO_ID") REFERENCES "SV_USUARIO" ("USUARIO_ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "SV_USUARIO_ROL_SEDE" ADD CONSTRAINT "REFROL5" FOREIGN KEY ("ROL_CODE") REFERENCES "SV_ROL" ("ROL_CODE") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "SV_USUARIO_ROL_SEDE" ADD CONSTRAINT "REFSEDE6" FOREIGN KEY ("SEDE_ID") REFERENCES "SV_SEDE" ("SEDE_ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;