CREATE OR REPLACE VIEW VIEW_PERSONA_RESTRINGIDA_REPORT AS
SELECT
    -- Información básica de la persona restringida (campos directos sin alias)
    pr.PERSONA_RESTRINGIDA_ID,
    pr.NUMERO_DOCUMENTO,
    pr.LICENCIA_CONDUCIR,
    pr.NOMBRE_COMPLETO,
    pr.USUARIO_REPORTA,
    pr.RESTRINGIDO_EL,
    pr.RESTRINGIDO_HASTA,
    pr.OBSERVACIONES,

    -- Foreign Keys (campos directos sin alias)
    pr.TIPO_DOCUMENTO_IDENTIDAD_CODE,
    pr.SEDE_ORIGINADORA_ID,

    -- Información de SV_TIPO_DOCUMENTO_IDENTIDAD - prefijo TDI_
    tdi.NAME AS TDI_NOMBRE,

    -- Información de SV_SEDE - prefijo SEDE_
    s.NAME AS SEDE_NOMBRE,
    s.AMBITO AS SEDE_AMBITO,

    -- Campos calculados útiles
    CASE
        WHEN pr.RESTRINGIDO_HASTA IS NULL THEN TRUE
        WHEN CURRENT_TIMESTAMP <= pr.RESTRINGIDO_HASTA THEN TRUE
        ELSE FALSE
    END AS RESTRICCION_ACTIVA,

    -- Días restantes de restricción (null si es indefinida, positivo si activa, negativo si vencida)
    CASE
        WHEN pr.RESTRINGIDO_HASTA IS NULL THEN NULL
        ELSE DAYS_BETWEEN(CURRENT_TIMESTAMP, pr.RESTRINGIDO_HASTA)
    END AS DIAS_RESTRICCION,

    -- Tipo de restricción
    CASE
        WHEN pr.RESTRINGIDO_HASTA IS NULL THEN 'INDEFINIDA'
        WHEN CURRENT_TIMESTAMP <= pr.RESTRINGIDO_HASTA THEN 'TEMPORAL'
        ELSE 'VENCIDA'
    END AS TIPO_RESTRICCION

FROM SV_PERSONA_RESTRINGIDA pr

-- Relaciones LEFT JOIN
LEFT JOIN SV_TIPO_DOCUMENTO_IDENTIDAD tdi ON pr.TIPO_DOCUMENTO_IDENTIDAD_CODE = tdi.TIPO_DOCUMENTO_IDENTIDAD_CODE
LEFT JOIN SV_SEDE s ON pr.SEDE_ORIGINADORA_ID = s.SEDE_ID

WHERE pr.IS_DELETED = FALSE;



-- Consultas de ejemplo:
-- SELECT * FROM VIEW_PERSONA_RESTRINGIDA_REPORT
-- SELECT * FROM VIEW_PERSONA_RESTRINGIDA_REPORT WHERE RESTRICCION_ACTIVA = TRUE
-- SELECT * FROM VIEW_PERSONA_RESTRINGIDA_REPORT WHERE TIPO_RESTRICCION = 'INDEFINIDA'
-- SELECT * FROM VIEW_PERSONA_RESTRINGIDA_REPORT WHERE TIPO_RESTRICCION = 'TEMPORAL' ORDER BY DIAS_RESTRICCION
