CREATE OR REPLACE VIEW VIEW_ADJUNTO_REPORT AS
SELECT
    -- Información básica del adjunto (campos directos sin alias)
    a.ADJUNTO_ID,
    a.NOMBRE_ARCHIVO,
    a.ID_REPOSITORIO,
    a.CLASIFICATION,
    a.FECHA_DOCUMENTO,
    a.FECHA_VENCIMIENTO,
    a.RUTA_RELATIVA,
    a.SSO_COMENTARIO_REVISION,
    a.CA_COMENTARIO_REVISION,

    -- Foreign Keys (campos directos sin alias)
    a.PROVEEDOR_ID,
    a.TRABAJADOR_ID,
    a.TIPO_DOCUMENTO_PLANILLA_CODE,
    a.SOLICITUD_VISITA_ID,
    a.TIPO_ACTIVIDAD_ALTO_RIESGO_CODE,

    -- Información de SV_TIPO_DOCUMENTO_PLANILLA - prefijo TDP_
    tdp.DESCRIPTION AS TDP_DESCRIPCION,
    tdp.AMBITO AS TDP_AMBITO,
    tdp.INFLUENCIA AS TDP_INFLUENCIA,
    tdp.DEPENDENCIA AS TDP_DEPENDENCIA,
    tdp.CAMPO_PLANTILLA_LF AS TDP_CAMPO_PLANTILLA_LF,
    tdp.OBLIGATORIO AS TDP_OBLIGATORIO,
    tdp.VENCIMIENTO AS TDP_VENCIMIENTO,


    -- Campos calculados útiles
    CASE
        WHEN a.TRABAJADOR_ID IS NOT NULL THEN 'TRABAJADOR'
        WHEN a.PROVEEDOR_ID IS NOT NULL THEN 'PROVEEDOR'
        WHEN a.SOLICITUD_VISITA_ID IS NOT NULL THEN 'SOLICITUD_VISITA'
        ELSE 'OTRO'
        END AS TIPO_PROPIETARIO,

    -- Indicador de si el documento está vencido
    CASE
        WHEN tdp.VENCIMIENTO = TRUE AND a.FECHA_VENCIMIENTO IS NOT NULL AND CURRENT_DATE > a.FECHA_VENCIMIENTO
            THEN TRUE
        ELSE FALSE
        END AS DOCUMENTO_VENCIDO,

    -- Días restantes hasta vencimiento (null si no aplica)
    CASE
        WHEN tdp.VENCIMIENTO = TRUE AND a.FECHA_VENCIMIENTO IS NOT NULL
            THEN DAYS_BETWEEN(CURRENT_DATE, a.FECHA_VENCIMIENTO)
        ELSE NULL
    END AS DIAS_HASTA_VENCIMIENTO

FROM SV_ADJUNTO a
         LEFT JOIN SV_TIPO_DOCUMENTO_PLANILLA tdp ON a.TIPO_DOCUMENTO_PLANILLA_CODE = tdp.TIPO_DOCUMENTO_PLANILLA_CODE

WHERE a.IS_DELETED = FALSE;



-- SELECT * FROM VIEW_ADJUNTO_REPORT
-- SELECT * FROM VIEW_ADJUNTO_REPORT WHERE DOCUMENTO_VENCIDO = TRUE
-- SELECT * FROM VIEW_ADJUNTO_REPORT WHERE TIPO_PROPIETARIO = 'TRABAJADOR'

