CREATE OR REPLACE VIEW VIEW_SOLICITUD_VISITA_REPORT AS
SELECT
    -- Información básica de la solicitud de visita (campos directos sin alias)
    sv.SOLICITUD_VISITA_ID,
    sv.CODIGO_VISITA,
    sv.CODIGO_SISTEMA_EXTERNO,
    sv.FECHA_INICIO,
    sv.FECHA_FIN,
    sv.MOTIVO_VISITA,
    sv.FECHA_APROBACION_PERSONA_VISITADA,
    sv.FECHA_OBSERVACION_ADMINISTRADOR,
    sv.OBSERVACIONES,
    sv.NRO_ORDEN_SERVICIO,

    -- Indicadores (campos directos sin alias)
    sv.IND_ACTIVIDAD_ALTO_RIESGO,
    sv.IND_ACTIVIDAD_A_BORDO,
    sv.IND_REQUIERE_ANDAMIOS,
    sv.IND_REQUIERE_GRUA,
    sv.IND_REQUIERE_EQUIPOS_MOVILES,
    sv.IND_TRABAJO_BUCEO,

    -- Motivos y descargos SSO y CA (campos directos sin alias)
    sv.SSO_MOTIVO,
    sv.SSO_DESCARGO,
    sv.CA_MOTIVO,
    sv.CA_DESCARGO,

    -- Foreign Keys (campos directos sin alias)
    sv.ESTADO_SSO_CODE,
    sv.ESTADO_CALIDAD_AMBIENTAL_CODE,
    sv.ESTADO_SOLICITUD_VISITA_CODE,
    sv.SEDE_ID,
    sv.PROVEEDOR_ID,
    sv.PERSONAL_ID,

    -- Información de SV_SEDE - prefijo SEDE_
    s.NAME AS SEDE_NOMBRE,
    s.AMBITO AS SEDE_AMBITO,

    -- Información de SV_PERSONAL - prefijo PERSONAL_
    per.NOMBRE_USUARIO AS PERSONAL_NOMBRE_USUARIO,
    per.USUARIO AS PERSONAL_USUARIO,

    -- Información de SV_PROVEEDOR - prefijo PROVEEDOR_
    p.NOMBRE_FISCAL AS PROVEEDOR_NOMBRE_FISCAL,
    p.NRO_DOCUMENTO_IDENTIDAD AS PROVEEDOR_NRO_DOCUMENTO_IDENTIDAD,
    p.EMAIL AS PROVEEDOR_EMAIL,
    p.CONTACTO_PRINCIPAL AS PROVEEDOR_CONTACTO_PRINCIPAL,

    -- Información de SV_ESTADO_SOLICITUD_VISITA - prefijo ESV_
    esv.NAME AS ESV_NOMBRE,

    -- Información de SV_ESTADO_SSO - prefijo SSO_ESTADO_
    esso.NAME AS SSO_ESTADO_NOMBRE,
    esso.DESCRIPTION AS SSO_ESTADO_DESCRIPCION,

    -- Información de SV_ESTADO_CALIDAD_AMBIENTAL - prefijo CA_ESTADO_
    eca.NAME AS CA_ESTADO_NOMBRE,
    eca.DESCRIPTION AS CA_ESTADO_DESCRIPCION,

    -- Información de SV_SOLICITUD_VISITA_TIPO_ACTIVIDAD_ALTO_RIESGO
    (
        SELECT STRING_AGG(tar.DESCRIPTION, ', ')
        FROM SV_SOLICITUD_VISITA_TIPO_ACTIVIDAD_ALTO_RIESGO ttar
                 INNER JOIN SV_TIPO_ACTIVIDAD_ALTO_RIESGO tar ON ttar.TIPO_ACTIVIDAD_ALTO_RIESGO_CODE = tar.TIPO_ACTIVIDAD_ALTO_RIESGO_CODE
        WHERE ttar.SOLICITUD_VISITA_ID = sv.SOLICITUD_VISITA_ID
          AND ttar.IS_ACTIVE = true
          AND tar.IS_ACTIVE = true
    ) AS TAR_DESCRIPCIONES,

    -- Campos calculados

    -- Número de días de la visita (mínimo 1 día)
    CASE
        WHEN sv.FECHA_INICIO IS NOT NULL AND sv.FECHA_FIN IS NOT NULL THEN
            GREATEST(DAYS_BETWEEN(sv.FECHA_INICIO, sv.FECHA_FIN), 1)
        ELSE NULL
        END AS N_DIAS,

    -- Número de trabajadores en la visita
    (
        SELECT COUNT(DISTINCT svd.TRABAJADOR_ID)
        FROM SV_SOLICITUD_VISITA_DETALLE svd
        WHERE svd.SOLICITUD_VISITA_ID = sv.SOLICITUD_VISITA_ID
          AND svd.IS_DELETED = FALSE
    ) AS N_TRABAJADORES,

    -- IDs de áreas visitadas (lista concatenada para filtrado) - prefijo AREAS_
    (
        SELECT STRING_AGG(sva.AREA_AUTORIZADORA_ID, ',')
        FROM SV_SOLICITUD_VISITA_AREA_AUTORIZADORA sva
        WHERE sva.SOLICITUD_VISITA_ID = sv.SOLICITUD_VISITA_ID
          AND sva.IS_ACTIVE = true
    ) AS AREAS_IDS,

    -- Áreas visitadas (lista concatenada de nombres de áreas) - prefijo AREAS_
    (
        SELECT STRING_AGG(a.NAME, ', ')
        FROM SV_SOLICITUD_VISITA_AREA_AUTORIZADORA sva
                 INNER JOIN SV_AREA a ON sva.AREA_AUTORIZADORA_ID = a.AREA_ID
        WHERE sva.SOLICITUD_VISITA_ID = sv.SOLICITUD_VISITA_ID
          AND sva.IS_ACTIVE = true
    ) AS AREAS_NOMBRES,

    -- IDs de zonas visitadas (lista concatenada para filtrado) - prefijo ZONAS_
    (
        SELECT STRING_AGG(svz.SOLICITUD_VISITA_ZONA_ID, ',')
        FROM SV_SOLICITUD_VISITA_ZONA svz
        WHERE svz.SOLICITUD_VISITA_ID = sv.SOLICITUD_VISITA_ID
          AND svz.IS_ACTIVE = true
    ) AS ZONAS_IDS,

    -- Zonas visitadas (lista concatenada de nombres de zonas) - prefijo ZONAS_
    (
        SELECT STRING_AGG(z.NAME, ', ')
        FROM SV_SOLICITUD_VISITA_ZONA svz
                 INNER JOIN SV_ZONA z ON svz.ZONA_ID = z.ZONA_ID
        WHERE svz.SOLICITUD_VISITA_ID = sv.SOLICITUD_VISITA_ID
          AND svz.IS_ACTIVE = true
    ) AS ZONAS_NOMBRES

FROM SV_SOLICITUD_VISISTA sv

-- Relaciones LEFT JOIN
         LEFT JOIN SV_SEDE s ON sv.SEDE_ID = s.SEDE_ID
         LEFT JOIN SV_PERSONAL per ON sv.PERSONAL_ID = per.PERSONAL_ID
         LEFT JOIN SV_PROVEEDOR p ON sv.PROVEEDOR_ID = p.PROVEEDOR_ID
         LEFT JOIN SV_ESTADO_SOLICITUD_VISITA esv ON sv.ESTADO_SOLICITUD_VISITA_CODE = esv.ESTADO_SOLICITUD_VISITA_CODE
         LEFT JOIN SV_ESTADO_SSO esso ON sv.ESTADO_SSO_CODE = esso.ESTADO_SSO_CODE
         LEFT JOIN SV_ESTADO_CALIDAD_AMBIENTAL eca ON sv.ESTADO_CALIDAD_AMBIENTAL_CODE = eca.ESTADO_CALIDAD_AMBIENTAL_CODE

WHERE sv.IS_DELETED = FALSE;



-- Consultas de ejemplo:
-- SELECT * FROM VIEW_SOLICITUD_VISITA_REPORT
-- SELECT * FROM VIEW_SOLICITUD_VISITA_REPORT WHERE ESTADO_SOLICITUD_VISITA_CODE = 'PRELIMINAR_PROVEEDOR'
-- SELECT * FROM VIEW_SOLICITUD_VISITA_REPORT WHERE TRABAJADORES_DNIS LIKE '%12345678%'
-- SELECT * FROM VIEW_SOLICITUD_VISITA_REPORT WHERE TRABAJADORES_NOMBRES LIKE '%JUAN%'
-- SELECT * FROM VIEW_SOLICITUD_VISITA_REPORT WHERE SEDE_ID = 'id-sede-123'
-- SELECT * FROM VIEW_SOLICITUD_VISITA_REPORT WHERE FECHA_INICIO BETWEEN '2025-01-01' AND '2025-12-31'
