INSERT INTO SV_ESTADO_SSO (ESTADO_SSO_CODE, NAME, DESCRIPTION, IS_DELETED, VERSION) VALUES('ST_SSO_0001', 'PRELIMINAR', 'Estado preliminar para SSO', false, 0);
INSERT INTO SV_ESTADO_SSO (ESTADO_SSO_CODE, NAME, DESCRIPTION, IS_DELETED, VERSION) VALUES('ST_SSO_0002', 'APTO', 'Apto para SSO', false, 0);
INSERT INTO SV_ESTADO_SSO (ESTADO_SSO_CODE, NAME, DESCRIPTION, IS_DELETED, VERSION) VALUES('ST_SSO_0003', 'NO APTO', 'No apto para SSO', false, 0);

-- ESTADOS PROPUESTOS

INSERT INTO SV_ESTADO_SSO
(ESTADO_SSO_CODE, NAME, DESCRIPTION, IS_DELETED, VERSION)
VALUES ('EST_EN_PROCESO', 'EN PROCESO', 'Estado en proceso de revisión', FALSE, 0);

INSERT INTO SV_ESTADO_SSO
(ESTADO_SSO_CODE, NAME, DESCRIPTION, IS_DELETED, VERSION)
VALUES ('EST_PENDIENTE', 'PENDIENTE', 'Pendiente de aprobación por SSO', FALSE, 0);

INSERT INTO SV_ESTADO_SSO
(ESTADO_SSO_CODE, NAME, DESCRIPTION, IS_DELETED, VERSION)
VALUES ('EST_OBSERVADO', 'OBSERVADO', 'Observado: requiere corrección', FALSE, 0);

INSERT INTO SV_ESTADO_SSO
(ESTADO_SSO_CODE, NAME, DESCRIPTION, IS_DELETED, VERSION)
VALUES ('EST_APROBADO', 'APROBADO', 'Aprobado por SSO', FALSE, 0);

INSERT INTO SV_ESTADO_SSO
(ESTADO_SSO_CODE, NAME, DESCRIPTION, IS_DELETED, VERSION)
VALUES ('EST_RECHAZADO', 'RECHAZADO', 'Rechazado por SSO', FALSE, 0);

INSERT INTO SV_ESTADO_SSO
(ESTADO_SSO_CODE, NAME, DESCRIPTION, IS_DELETED, VERSION)
VALUES ('EST_CERRADO', 'CERRADO', 'Proceso cerrado', FALSE, 0);

INSERT INTO SV_ESTADO_SSO
(ESTADO_SSO_CODE, NAME, DESCRIPTION, IS_DELETED, VERSION)
VALUES ('EST_ANULADO', 'ANULADO', 'Registro anulado', FALSE, 0);

INSERT INTO SV_ESTADO_SSO
(ESTADO_SSO_CODE, NAME, DESCRIPTION, IS_DELETED, VERSION)
VALUES ('EST_FINALIZADO', 'FINALIZADO', 'Proceso finalizado completamente', FALSE, 0);
