INSERT INTO SV_ESTADO_CALIDAD_AMBIENTAL (ESTADO_CALIDAD_AMBIENTAL_CODE, NAME, DESCRIPTION, IS_DELETED, VERSION) VALUES('ST_CA_0001', 'PRELIMINAR', 'Estado preliminar para Calidad Ambiental', false, 0);
INSERT INTO SV_ESTADO_CALIDAD_AMBIENTAL (ESTADO_CALIDAD_AMBIENTAL_CODE, NAME, DESCRIPTION, IS_DELETED, VERSION) VALUES('ST_CA_0002', 'APTO', 'Apto para Calidad Ambiental', false, 0);
INSERT INTO SV_ESTADO_CALIDAD_AMBIENTAL (ESTADO_CALIDAD_AMBIENTAL_CODE, NAME, DESCRIPTION, IS_DELETED, VERSION) VALUES('ST_CA_0003', 'NO APTO', 'No apto para Calidad Ambiental', false, 0);

-- ESTADOS PROPUESTOS

INSERT INTO SV_ESTADO_CALIDAD_AMBIENTAL
(ESTADO_CALIDAD_AMBIENTAL_CODE, NAME, DESCRIPTION, IS_DELETED, VERSION)
VALUES ('EST_EN_PROCESO', 'EN PROCESO', 'Estado en proceso de revisión', FALSE, 0);

INSERT INTO SV_ESTADO_CALIDAD_AMBIENTAL
(ESTADO_CALIDAD_AMBIENTAL_CODE, NAME, DESCRIPTION, IS_DELETED, VERSION)
VALUES ('EST_PENDIENTE', 'PENDIENTE', 'Pendiente de aprobación por Calidad Ambiental', FALSE, 0);

INSERT INTO SV_ESTADO_CALIDAD_AMBIENTAL
(ESTADO_CALIDAD_AMBIENTAL_CODE, NAME, DESCRIPTION, IS_DELETED, VERSION)
VALUES ('EST_OBSERVADO', 'OBSERVADO', 'Observado: requiere corrección', FALSE, 0);

INSERT INTO SV_ESTADO_CALIDAD_AMBIENTAL
(ESTADO_CALIDAD_AMBIENTAL_CODE, NAME, DESCRIPTION, IS_DELETED, VERSION)
VALUES ('EST_APROBADO', 'APROBADO', 'Aprobado por Calidad Ambiental', FALSE, 0);

INSERT INTO SV_ESTADO_CALIDAD_AMBIENTAL
(ESTADO_CALIDAD_AMBIENTAL_CODE, NAME, DESCRIPTION, IS_DELETED, VERSION)
VALUES ('EST_RECHAZADO', 'RECHAZADO', 'Rechazado por Calidad Ambiental', FALSE, 0);

INSERT INTO SV_ESTADO_CALIDAD_AMBIENTAL
(ESTADO_CALIDAD_AMBIENTAL_CODE, NAME, DESCRIPTION, IS_DELETED, VERSION)
VALUES ('EST_CERRADO', 'CERRADO', 'Proceso cerrado', FALSE, 0);

INSERT INTO SV_ESTADO_CALIDAD_AMBIENTAL
(ESTADO_CALIDAD_AMBIENTAL_CODE, NAME, DESCRIPTION, IS_DELETED, VERSION)
VALUES ('EST_ANULADO', 'ANULADO', 'Registro anulado', FALSE, 0);

INSERT INTO SV_ESTADO_CALIDAD_AMBIENTAL
(ESTADO_CALIDAD_AMBIENTAL_CODE, NAME, DESCRIPTION, IS_DELETED, VERSION)
VALUES ('EST_FINALIZADO', 'FINALIZADO', 'Proceso finalizado completamente', FALSE, 0);
