INSERT INTO SV_ROL (ROL_CODE, ROL_NAME, ROL_DESCRIPTION, IS_DELETED, VERSION)
VALUES('controlprov_sso', 'SSO', 'SSO', false, 0);

INSERT INTO SV_ROL (ROL_CODE, ROL_NAME, ROL_DESCRIPTION, IS_DELETED, VERSION)
VALUES('controlprov_amb', 'CALIDAD AMBIENTAL', 'Calidad ambiental', false, 0);

INSERT INTO SV_ROL (ROL_CODE, ROL_NAME, ROL_DESCRIPTION, IS_DELETED, VERSION)
VALUES('controlprov_secpatr', 'SEGURIDAD PATRIMONIAL', 'Seguridad Patrimonial', false, 0);

INSERT INTO SV_ROL (ROL_CODE, ROL_NAME, ROL_DESCRIPTION, IS_DELETED, VERSION)
VALUES('controlprov_admin', 'ADMINISTRACION', 'Administracion', false, 0);

INSERT INTO SV_ROL (ROL_CODE, ROL_NAME, ROL_DESCRIPTION, IS_DELETED, VERSION)
VALUES('controlprov_creaprov', 'CREA PROVEEDOR', 'Gestion de Proveedores', false, 0);

INSERT INTO SV_ROL (ROL_CODE, ROL_NAME, ROL_DESCRIPTION, IS_DELETED, VERSION)
VALUES('controlprov_prov', 'PROVEEDOR', 'Proveedor', false, 0);