INSERT INTO SV_TIPO_DOCUMENTO_IDENTIDAD (TIPO_DOCUMENTO_IDENTIDAD_CODE, NAME, IS_ACTIVE, EXPRESION_REGULAR, IS_DELETED, VERSION)
VALUES ('TDI_00001', 'DNI', TRUE, '', FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_IDENTIDAD (TIPO_DOCUMENTO_IDENTIDAD_CODE, NAME, IS_ACTIVE, EXPRESION_REGULAR, IS_DELETED, VERSION)
VALUES ('TDI_00002', 'Carnet de Extranjería', TRUE, '', FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_IDENTIDAD (TIPO_DOCUMENTO_IDENTIDAD_CODE, NAME, IS_ACTIVE, EXPRESION_REGULAR, IS_DELETED, VERSION)
VALUES ('TDI_00003', 'Pasaporte', TRUE, '', FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_IDENTIDAD (TIPO_DOCUMENTO_IDENTIDAD_CODE, NAME, IS_ACTIVE, EXPRESION_REGULAR, IS_DELETED, VERSION)
VALUES ('TDI_00004', 'RUC', TRUE, '', FALSE, 0);