INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES (TRUE, 'Politica de SST', 'SSO', '', 'Empresa', 'Tipo de documento Empresa SSO', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('2', 'Plan anual de SST', 'SSO', '', 'Empresa', 'Tipo de documento Empresa SSO', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('3', 'Programa anual de SST', 'SSO', '', 'Empresa', 'Tipo de documento Empresa SSO', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('4', 'Programa de simulacros', 'SSO', '', 'Empresa', 'Tipo de documento Empresa SSO', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('5', 'Programa anual de capacitación', 'SSO', '', 'Empresa', 'Tipo de documento Empresa SSO', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('6', 'RISST', 'SSO', '', 'Empresa', 'Tipo de documento Empresa SSO', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('7', 'Acta de instalación CSST', 'SSO', '', 'Empresa', 'Tipo de documento Empresa SSO', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('8', 'Procedimiento de investigación', 'SSO', '', 'Empresa', 'Tipo de documento Empresa SSO', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('9', 'Protocolo de examen medico ocupacional', 'SSO', '', 'Empresa', 'Tipo de documento Empresa SSO', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('10', 'Declaracion jurada', 'SSO', '', 'Empresa', 'Tipo de documento Empresa SSO', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('11', 'Procedimiento AR espacio confinado', 'SSO', 'Trabajo en espacio confinado', 'Empresa_AR', 'Sustento Actividad de alto riesgo Empresa', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('12', 'Procedimiento AR sustancias químicas', 'SSO', 'Trabajo con sustancias químicas', 'Empresa_AR', 'Sustento Actividad de alto riesgo Empresa', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('13', 'Procedimiento AR altura', 'SSO', 'Trabajo en altura', 'Empresa_AR', 'Sustento Actividad de alto riesgo Empresa', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('14', 'Procedimiento AR caliente', 'SSO', 'Trabajo en caliente', 'Empresa_AR', 'Sustento Actividad de alto riesgo Empresa', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('15', 'Procedimiento AR izaje', 'SSO', 'Trabajo de izaje', 'Empresa_AR', 'Sustento Actividad de alto riesgo Empresa', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('16', 'Procedimiento AR excavaciones y zanjas', 'SSO', 'Trabajo de excavaciones y zanjas', 'Empresa_AR', 'Sustento Actividad de alto riesgo Empresa', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('17', 'Procedimiento AR energía peligrosa', 'SSO', 'Trabajo con energía peligrosa', 'Empresa_AR', 'Sustento Actividad de alto riesgo Empresa', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('18', 'Procedimiento AR buceo', 'SSO', 'Trabajo de buceo', 'Empresa_AR', 'Sustento Actividad de alto riesgo Empresa', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('19', 'Plan de respuesta a emergencia', 'SSO', '', 'Empresa_AR', 'Sustento Actividad de alto riesgo Empresa', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('20', 'Analisis de trabajo seguro', 'SSO', '', 'Empresa_AR', 'Sustento Actividad de alto riesgo Empresa', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('21', 'Permiso de DICAPI', 'SSO', '', 'Empresa_AB', 'Sustento Actividad a bordo Empresa', TRUE, TRUE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('22', 'Registro de Capacitacion IPERC', 'SSO', '', 'Trabajador', 'Tipo de documento Trabajador SSO', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('23', 'Registro de Entrega EPPS', 'SSO', '', 'Trabajador', 'Tipo de documento Trabajador SSO', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('24', 'Constancia de SCTR Pension y Salud', 'SSO', '', 'Trabajador', 'Tipo de documento Trabajador SSO', TRUE, TRUE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('25', 'EMO', 'SSO', '', 'Trabajador', 'Tipo de documento Trabajador SSO', TRUE, TRUE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('26', 'Contrato', 'SSO', '', 'Trabajador', 'Tipo de documento Trabajador SSO', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('27', 'Induccion SSO', 'SSO', '', 'Trabajador', 'Tipo de documento Trabajador SSO', TRUE, TRUE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('28', 'Formato resumen de EMO', 'SSO', '', 'Trabajador', 'Tipo de documento Trabajador SSO', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('29', 'Registro de capacitacion espacio confinado', 'SSO', 'Trabajo en espacio confinado', 'Trabajador_AR', 'Sustento Actividad de alto riesgo Tbjd', TRUE, TRUE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('30', 'Registro de capacitacion sustancias quimicas', 'SSO', 'Trabajo con sustancias químicas', 'Trabajador_AR', 'Sustento Actividad de alto riesgo Tbjd', TRUE, TRUE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('31', 'Registro de capacitacion trabajo en altura', 'SSO', 'Trabajo en altura', 'Trabajador_AR', 'Sustento Actividad de alto riesgo Tbjd', TRUE, TRUE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('32', 'Registro de capacitacion trabajo en caliente', 'SSO', 'Trabajo en caliente', 'Trabajador_AR', 'Sustento Actividad de alto riesgo Tbjd', TRUE, TRUE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('33', 'Registro de capacitacion trabajo de izaje', 'SSO', 'Trabajo de izaje', 'Trabajador_AR', 'Sustento Actividad de alto riesgo Tbjd', TRUE, TRUE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('34', 'Registro de capacitacion excavaciones y zanjas', 'SSO', 'Trabajo de excavaciones y zanjas', 'Trabajador_AR', 'Sustento Actividad de alto riesgo Tbjd', TRUE, TRUE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('35', 'Registro de capacitacion energía peligrosa', 'SSO', 'Trabajo con energía peligrosa', 'Trabajador_AR', 'Sustento Actividad de alto riesgo Tbjd', TRUE, TRUE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('36', 'Registro de capacitacion trabajo de buceo', 'SSO', 'Trabajo de buceo', 'Trabajador_AR', 'Sustento Actividad de alto riesgo Tbjd', TRUE, TRUE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('37', 'CV Prevencionista', 'SSO', '', 'Trabajador_PR', 'Sustento Prevencionista', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('38', 'Memoria Descriptiva', 'SSO', '', 'Servicio', 'Tipo de documento Servicio SSO', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('39', 'Formato de relacion de trabajadores', 'SSO', '', 'Servicio', 'Tipo de documento Servicio SSO', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('40', 'Matriz IPERC', 'SSO', '', 'Servicio', 'Tipo de documento Servicio SSO', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('41', 'Registro de inspeccion equipos de trabajo y herramientas', 'SSO', '', 'Servicio', 'Tipo de documento Servicio SSO', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('42', 'Registro de inspeccion equipos de seguridad', 'SSO', '', 'Servicio', 'Tipo de documento Servicio SSO', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('43', 'Registro de inspeccion preuso de equipos de trabajo y herramientas', 'SSO', '', 'Servicio_AR', 'Sustento Actividad de alto riesgo Servicio', FALSE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('44', 'Registro de inspeccion preuso de equipos de seguridad', 'SSO', '', 'Servicio_AR', 'Sustento Actividad de alto riesgo Servicio', FALSE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('45', 'Permiso para realizar trabajos a bordo', 'SSO', '', 'Servicio_AB', 'Sustento Actividad a bordo Servicio', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('46', 'Certificado de andamios homologado', 'SSO', '', 'Servicio_AD', 'Sustento andamios', TRUE, TRUE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('47', 'Certificado de operatividad del vehículo', 'SSO', '', 'Servicio_GR', 'Sustento grúa', TRUE, TRUE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('48', 'Certificado del operador', 'SSO', '', 'Servicio_GR', 'Sustento grúa', TRUE, TRUE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('49', 'Inspeccion de preuso del equipo', 'SSO', '', 'Servicio_GR', 'Sustento grúa', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('50', 'Certificado del Rigger', 'SSO', '', 'Servicio_GR', 'Sustento grúa', TRUE, TRUE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('51', 'Plan de izaje', 'SSO', '', 'Servicio_GR', 'Sustento grua', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('52', 'Certificado de operatividad del vehiculo', 'SSO', '', 'Servicio_EM', 'Sustento equipos móviles', TRUE, TRUE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('53', 'Certificado del operador según el equipo', 'SSO', '', 'Servicio_EM', 'Sustento equipos móviles', TRUE, TRUE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('54', 'Plan de mantenimiento preventivo', 'SSO', '', 'Servicio_EM', 'Sustento equipos móviles', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('55', 'Inspeccion de preuso del equipo', 'SSO', '', 'Servicio_EM', 'Sustento equipos moviles', TRUE, FALSE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('56', 'Carne de personal acuatico', 'SSO', '', 'Servicio_BU', 'Sustento trabajo buceo', TRUE, TRUE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('57', 'Matriz IAA', 'Calidad Ambiental', '', 'Empresa', 'Tipo de documento Empresa CA', TRUE, TRUE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('58', 'Registro de capacitación CA', 'Calidad Ambiental', '', 'Empresa', 'Tipo de documento Empresa CA', TRUE, TRUE, FALSE, 0);

INSERT INTO SV_TIPO_DOCUMENTO_PLANILLA
(TIPO_DOCUMENTO_PLANILLA_CODE, DESCRIPTION, AMBITO, DEPENDENCIA, INFLUENCIA, CAMPO_PLANTILLA_LF, OBLIGATORIO, VENCIMIENTO, IS_DELETED, VERSION)
VALUES ('59', 'Registro de inducción CA', 'Calidad Ambiental', '', 'Servicio', 'Tipo de documento Servicio CA', TRUE, TRUE, FALSE, 0);
