INSERT INTO SV_TIPO_ACTIVIDAD_ALTO_RIESGO (TIPO_ACTIVIDAD_ALTO_RIESGO_CODE, DESCRIPTION, IS_ACTIVE, IS_DELETED, VERSION)
VALUES ('TAAR_00001', 'Trabajo en espacio confinado', TRUE, FALSE, 0);

INSERT INTO SV_TIPO_ACTIVIDAD_ALTO_RIESGO (TIPO_ACTIVIDAD_ALTO_RIESGO_CODE, DESCRIPTION, IS_ACTIVE, IS_DELETED, VERSION)
VALUES ('TAAR_00002', 'Trabajo con sustancias químicas', TRUE, FALSE, 0);

INSERT INTO SV_TIPO_ACTIVIDAD_ALTO_RIESGO (TIPO_ACTIVIDAD_ALTO_RIESGO_CODE, DESCRIPTION, IS_ACTIVE, IS_DELETED, VERSION)
VALUES ('TAAR_00003', 'Trabajo en altura', TRUE, FALSE, 0);

INSERT INTO SV_TIPO_ACTIVIDAD_ALTO_RIESGO (TIPO_ACTIVIDAD_ALTO_RIESGO_CODE, DESCRIPTION, IS_ACTIVE, IS_DELETED, VERSION)
VALUES ('TAAR_00004', 'Trabajo en caliente', TRUE, FALSE, 0);

INSERT INTO SV_TIPO_ACTIVIDAD_ALTO_RIESGO (TIPO_ACTIVIDAD_ALTO_RIESGO_CODE, DESCRIPTION, IS_ACTIVE, IS_DELETED, VERSION)
VALUES ('TAAR_00005', 'Trabajo de izaje', TRUE, FALSE, 0);

INSERT INTO SV_TIPO_ACTIVIDAD_ALTO_RIESGO (TIPO_ACTIVIDAD_ALTO_RIESGO_CODE, DESCRIPTION, IS_ACTIVE, IS_DELETED, VERSION)
VALUES ('TAAR_00006', 'Trabajo de excavaciones y zanjas', TRUE, FALSE, 0);

INSERT INTO SV_TIPO_ACTIVIDAD_ALTO_RIESGO (TIPO_ACTIVIDAD_ALTO_RIESGO_CODE, DESCRIPTION, IS_ACTIVE, IS_DELETED, VERSION)
VALUES ('TAAR_00007', 'Trabajo con energía peligrosa', TRUE, FALSE, 0);

INSERT INTO SV_TIPO_ACTIVIDAD_ALTO_RIESGO (TIPO_ACTIVIDAD_ALTO_RIESGO_CODE, DESCRIPTION, IS_ACTIVE, IS_DELETED, VERSION)
VALUES ('TAAR_00008', 'Trabajo de buceo', TRUE, FALSE, 0);
